In [1]:
'''
@Author: Su, Ming Yi
@Date: 01/22/2019
@Goal: convert RGB image to gray image
'''

'\n@Author: Su, Ming Yi\n@Date: 01/22/2019\n@Goal: convert RGB image to gray image\n'

In [17]:
import cv2
import numpy as np

In [18]:
image = cv2.imread('..//Output//Train_Data_Summary//0116_Symbol_RGB//musical_symbol_bass_clef_10x10.png')
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
#cv2.imwrite('gray_image.png',gray_image)

In [32]:
#print(image.shape[:3])
#print(image.shape[:])
#print(gray_image.shape[:])
height, width = gray_image.shape[:2]
#print(height, width)
gray_image = np.reshape(gray_image, (height, width, 1))

print(gray_image.shape[:])

(2000, 800, 1)


In [25]:
a = np.arange(6).reshape((3, 2))
print(a)
print(np.reshape(a, (2, 3, 1)))

[[0 1]
 [2 3]
 [4 5]]
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]]
